import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import App from '../../react-router-v5/src/App'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App ith next-router and react-router</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App />
    </>
  )
}

export default Home
